fix(): make release type required

diff --git a/.github/workflows/releasenotes.js.yml b/.github/workflows/releasenotes.js.yml
--- a/.github/workflows/releasenotes.js.yml
+++ b/.github/workflows/releasenotes.js.yml
@@ -10,7 +10,8 @@ on:
         description: 'Enter release tag number'
         required: true
       release_type:
-        description: 'Enter release type (patch, minor, or major)'
+        description: 'Enter release type (patch, minor, major, or none)'
+        required: true
       passcode:
         description: 'Enter passcode'
         required: true
@@ -55,17 +56,19 @@ jobs:
             git config --global user.email "noreply@remo.co"
             git config --global user.name "Release Notes"
             release_type=${{github.event.inputs.release_type}}
-            if [[ -z "$release_type" ]]; then
-              echo "No release type entered";
-              exit 1;
-            elif [[ ${{github.event.inputs.release_type}} == 'patch' ]]; then
+            if [[ ${{github.event.inputs.release_type}} == 'patch' ]]; then
               npx standard-version --no-verify --release-as patch
             elif [[ ${{github.event.inputs.release_type}}  == 'minor' ]]; then
               npx standard-version --no-verify --release-as minor
             elif [[ ${{github.event.inputs.release_type}}  == 'major' ]]; then
               npx standard-version --no-verify --release-as major
-            else
-              echo "Incorrect or empty release type. Received: ${{github.event.inputs.release_type}}"
+            elif [[ ${{github.event.inputs.release_type}}  == 'none' ]]; then
+              echo "Release type 'none' entered";
+              echo "Error: Either select a valid release type, or enter a different release tag"
+              exit 1;
+            else 
+              echo "Error: Either select a valid release type, or enter a different release tag"
+              exit 1;
             fi
             git push --follow-tags origin master
             bumped_release_tag=$(grep -m 1 -E "version" package.json | cut -c 15- | rev | cut -c 3- | rev)
